### ISSUE TITLE
I can't start the bot.

### ISSUE THREAD

**Issue by casperochecckk** [StrawHatHacker/Kiyo-Discord-Bot#2]
I can't figure out what's wrong.

Error: Environment variable "ENVIRONMENT" is neither "DEV" or "PRODUCTION"
    at Bot._registerSlashCommands (C:\Users\dedha\Desktop\афыв\src\classes\Bot.js:114:23)
    at Bot.start (C:\Users\dedha\Desktop\афыв\src\classes\Bot.js:201:20)

please help.

**Comment by StrawHatHacker** [comment]
A full `.env` file should look like this:

```
ENVIRONMENT=""
BOT_OWNER_ID=""
DEV_GUILD_ID=""
BOT_ID=""
DISCORD_BOT_TOKEN=""
DB_CONNECTION_STRING=""
OTAKUGIFS_API_KEY=""
```

The `ENVIRONMENT` field should be either "DEV" or "PRODUCTION". The only difference between those 2 values (for now) is that "DEV "only loads slash commands for your *DEV_GUILD_ID* server, which is faster than registering them globally(which is what the "PRODUCTION" value does).
Follow the steps at [Installation](https://github.com/StrawHatHacker/Kiyo-Discord-Bot#-installation)

**Comment by casperochecckk** [comment]
thx, prefix bot?

**Comment by casperochecckk** [comment]
slash commands no work

**Comment by StrawHatHacker** [comment]
> thx, what is the prefix of the bot?

The default prefix is `>`


> slash commands no work

This is not enough information for me to help you

**Comment by casperochecckk** [comment]
Let's go to discord? it's easier to explain and show there

**Comment by casperochecckk** [comment]
DiscordAPIError[20012]: You are not authorized to perform this action on this application
    at SequentialHandler.runRequest (C:\Users\dedha\Desktop\афыв\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\dedha\Desktop\афыв\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:99:20)
    at async Bot._registerSlashCommands (C:\Users\dedha\Desktop\афыв\src\classes\Bot.js:81:17)
    at async Bot.start (C:\Users\dedha\Desktop\афыв\src\classes\Bot.js:173:9) {
  rawError: {
    message: 'You are not authorized to perform this action on this application',
    code: 20012
  },
  code: 20012,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/895069498082734080/commands'
}
